export component AppUi inherits Window {
    width: 280px;
    height: 456px;

    in-out property <float> tilt_ratio: 0.5;

    Rectangle {
        background: #0055ff;

        Rectangle {
            x: 0px;
            y: 0px;
            width: parent.width;
            height: 42px;
            background: #ffcc00;
        }

        Rectangle {
            x: 16px;
            y: 70px;
            width: parent.width - 32px;
            height: 26px;
            background: #1a1a1a;
        }

        Rectangle {
            x: 16px;
            y: 70px;
            width: (parent.width - 32px) * root.tilt_ratio;
            height: 26px;
            background: #00ff66;
        }

        Rectangle {
            x: 24px;
            y: parent.height - 72px;
            width: parent.width - 48px;
            height: 40px;
            border-radius: 8px;
            background: #ffffff;
        }

        screen_touch := TouchArea {
            x: 0px;
            y: 0px;
            width: parent.width;
            height: parent.height;
        }

        Rectangle {
            visible: screen_touch.pressed;
            width: 20px;
            height: 20px;
            x: screen_touch.mouse-x - (self.width / 2);
            y: screen_touch.mouse-y - (self.height / 2);
            border-radius: 10px;
            background: #ff00aa;
        }
    }
}
