import { HomeView } from "home_view.slint";
import { ImuAppView } from "imu_app_view.slint";
import { TimerAppView } from "timer_app_view.slint";

export component AppUi inherits Window {
    width: 280px;
    height: 456px;

    in-out property <float> tilt_ratio: 0.5;
    in-out property <int> ui_seconds: 0;
    in-out property <int> active_page: 0;

    ui_timer := Timer {
        interval: 1s;
        running: true;
        triggered => {
            root.ui_seconds += 1;
        }
    }

    Rectangle {
        background: #050914;

        HomeView {
            x: 12px;
            y: 12px;
            width: parent.width - 24px;
            height: parent.height - 24px;
            visible: root.active_page == 0;
            tilt_ratio: root.tilt_ratio;
            ui_seconds: root.ui_seconds;
            open_imu => {
                root.active_page = 1;
            }
            open_timer => {
                root.active_page = 2;
            }
        }

        ImuAppView {
            x: 12px;
            y: 12px;
            width: parent.width - 24px;
            height: parent.height - 24px;
            visible: root.active_page == 1;
            tilt_ratio: root.tilt_ratio;
            back => {
                root.active_page = 0;
            }
        }

        TimerAppView {
            x: 12px;
            y: 12px;
            width: parent.width - 24px;
            height: parent.height - 24px;
            visible: root.active_page == 2;
            ui_seconds: root.ui_seconds;
            back => {
                root.active_page = 0;
            }
        }
    }
}
